Repository publicsuffix/list, pull requests merged in 2018-03, with the labels that each got.

#614 Removed se.com
  public_suffix_list.dat
Labels: pending-validation, waiting-followup

#628 Add AWS ElasticBeanstalk Osaka, JP region
  public_suffix_list.dat
Labels: r=sleevi

#512 Add myjino.ru
  public_suffix_list.dat
Labels: r=weppos

#522 Add ox.rs
  public_suffix_list.dat
Labels: r=weppos

#521 Include gwiddle.co.uk
  public_suffix_list.dat
Labels: r=weppos
