Repository publicsuffix/list, pull requests merged in 2018-04, with the labels that each got.

#634 Add cleverapps.io (Clever Cloud)
  public_suffix_list.dat
Labels: r=sleevi

#637 add azurecontainer.io
  public_suffix_list.dat
Labels: pending-validation

#622 cloud.muni.cz cloud subdomains
  public_suffix_list.dat
Labels: r=weppos

#615 Add YunoHost DynDns domains: nohost.me & noho.st
  public_suffix_list.dat
Labels: r=weppos

#514 lug.org.uk
  public_suffix_list.dat
Labels: waiting-followup

#585 Adding customer.speedpartner.de
  public_suffix_list.dat
Labels: r=weppos

#535 Adding ravendb.net subdomains
  public_suffix_list.dat
Labels: r=weppos
