Repository publicsuffix/list, pull requests merged in 2019-12, with the labels that each got.

#815 Reserved domains off
  public_suffix_list.dat
Labels: pending-validation, question

#811 Add_customer-oci.com
  public_suffix_list.dat
Labels: r=sleevi, waiting-followup

#868 Add qcx.io and *.sys.qcx.io
  public_suffix_list.dat
Labels: r=sleevi

#922 Add *.on-k3s.io
  public_suffix_list.dat
Labels: r=sleevi

#929 Add amsw.nl private domain to PSL
  public_suffix_list.dat
Labels: r=sleevi

#910 Add en-root.fr domain
  public_suffix_list.dat
Labels: r=sleevi

#919 add v.ua
  public_suffix_list.dat
Labels: r=sleevi

#914 Add Observable domain: observableusercontent.com.
  public_suffix_list.dat
Labels: r=sleevi

#931 Added adobeaemcloud domains
  public_suffix_list.dat
Labels: r=sleevi
