Repository publicsuffix/list, pull requests merged in 2019-05, with the labels that each got.

#746 Add nctu.me
  public_suffix_list.dat
Labels: r=sleevi

#543 Add Names.of.London Domains
  public_suffix_list.dat
Labels: r=sleevi

#732 Add private dynamic DNS solution for barsy.ca
  public_suffix_list.dat
Labels: r=sleevi

#733 Add Hakaran domains [caa.li | conf.se | fin.ci | free.hr | ua.rs | aero.al | pro.bj | fin.bj]
  public_suffix_list.dat
Labels: r=sleevi

#736 Add EduGit pages under edugit.org.
  public_suffix_list.dat
Labels: r=sleevi

#748 Add repl.co and repl.run
  public_suffix_list.dat
Labels: r=sleevi

#750 Add voorloper.cloud
  public_suffix_list.dat
Labels: r=sleevi

#755 Add Stackhero domain: stackhero-network.com
  public_suffix_list.dat
Labels: r=sleevi

#757 Add *.moonscale.io
  public_suffix_list.dat
Labels: r=sleevi

#761 Add user domains for Render: https://render.com
  public_suffix_list.dat
Labels: r=sleevi

#762 Add mo-siemens.io
  public_suffix_list.dat
Labels: r=sleevi

#764 Add onred.one
  public_suffix_list.dat
Labels: r=sleevi

#766 Add dweb.link
  public_suffix_list.dat
Labels: r=sleevi

#769 Add glitch.me to the PSL
  public_suffix_list.dat
Labels: r=sleevi

#770 Add Hostbip Registry Domains
  public_suffix_list.dat
Labels: r=sleevi

#785 Add wnext.app
  public_suffix_list.dat
Labels: r=sleevi

#790 Add loginline (.app, .dev, .io, .services, .site)
  public_suffix_list.dat
Labels: r=sleevi

#791 Add Clerk user domains
  public_suffix_list.dat
Labels: r=sleevi

#795 Add gehirn.ne.jp and usercontent.jp for Gehirn Inc.
  public_suffix_list.dat
Labels: r=sleevi

#801 Add KaasHosting
  public_suffix_list.dat
Labels: r=sleevi

#802 Add SRCF user domains: soc.srcf.net, user.srcf.net
  public_suffix_list.dat
Labels: r=sleevi

#804 Add häkkinen.fi
  public_suffix_list.dat
Labels: r=sleevi

#805 Add wafflecell.com
  public_suffix_list.dat
Labels: r=sleevi

#807 Add lab.ms
  public_suffix_list.dat
Labels: r=sleevi

#810 Add Linode Suffixes
  public_suffix_list.dat
Labels: r=sleevi

#816 Add Carrd suffixes
  public_suffix_list.dat
Labels: r=sleevi

#817 Add Zitcom domains
  public_suffix_list.dat
Labels: r=sleevi

#789 Add co.bn as Private Domain
  public_suffix_list.dat
Labels: r=sleevi

#759 Add b-data.io
  public_suffix_list.dat
Labels: r=sleevi

#812 Add azimuth.network and arvo.network
  public_suffix_list.dat
Labels: waiting-followup

#820 Add dyn53.io
  public_suffix_list.dat
Labels: r=sleevi

#827 Add king.host domains
  public_suffix_list.dat
Labels: r=sleevi

#814 Add Balena domains
  public_suffix_list.dat
Labels: r=sleevi

#829 Add cloudera.site
  public_suffix_list.dat
Labels: r=sleevi

#828 Add iobb.net
  public_suffix_list.dat
Labels: r=sleevi

#830 Add web.app for Google
  public_suffix_list.dat
Labels: pending-validation
