Repository publicsuffix/list, pull requests merged in 2019-07, with the labels that each got.

#840 Created record for qualifio
  public_suffix_list.dat
Labels: r=sleevi

#838 Add shopitsite.com
  public_suffix_list.dat
Labels: r=sleevi

#835 Add trycloudflare.com to Cloudflare's suffixes
  public_suffix_list.dat
Labels: r=sleevi

#826 Add iserv.dev for IServ GmbH
  public_suffix_list.dat
Labels: r=sleevi

#771 Update nymnom section
  public_suffix_list.dat
Labels: r=sleevi

#844 Add our Hosting service and Free domain service
  public_suffix_list.dat
Labels: r=sleevi, waiting-followup

#850 Add Yandex.Cloud section and Yandex object storage domains
  public_suffix_list.dat
Labels: r=sleevi

#846 Update Hostbip Section
  public_suffix_list.dat
Labels: r=sleevi

#847 Add *.webhare.dev
  public_suffix_list.dat
Labels: waiting-followup

#849 Add lelux.site
  public_suffix_list.dat
Labels: r=sleevi

#854 Update contact for SymfonyCloud
  public_suffix_list.dat
Labels: r=sleevi

#825 Update to include all current 3LD/4LD edu.au suffixes
  public_suffix_list.dat
Labels: pending-validation
