Repository publicsuffix/list, pull requests merged in 2020-08, with the labels that each got.

#1084 Add GOV.UK Pay test environment domain
  public_suffix_list.dat
Labels: pending-validation, question, r=dnsguru

#1080 Added mcpe.me
  public_suffix_list.dat
Labels: waiting-followup

#1074 Add Danger Science Group domains
  public_suffix_list.dat
Labels: waiting-followup

#1089 Update to ICANN and private SLDs on CentralNic registry platform
  public_suffix_list.dat
Labels: r=dnsguru, r=weppos, waiting-followup

#1086 Add small-web.org domain under Small Technology Foundation (private)
  public_suffix_list.dat
Labels: r=weppos
