Repository publicsuffix/list, pull requests merged in 2021-06, with the labels that each got.

#1339 Add postman dev domains
  public_suffix_list.dat
Labels: NOT IOS FB

#1343 Adding adimo.co.uk
  public_suffix_list.dat
Labels: NOT IOS FB

#1340 Add appudo.net
  public_suffix_list.dat
Labels: NOT IOS FB

#1337 Remove multibaas.app and multibaas.com
  public_suffix_list.dat
Labels: rollback

#1344 Add minisite.ms
  public_suffix_list.dat
Labels: NOT IOS FB

#1347 newgtlds.go : update Autopull - Added URL for the IANA PSL for #1325
  tools/newgtlds.go
Labels: waiting-followup

#1309 Add shop.brendly.rs
  public_suffix_list.dat
Labels: NOT IOS FB

#1353 Add ddns5.com to private section
  public_suffix_list.dat
Labels: NOT IOS FB

#1352 Removing private subregistry aprendemas.cl due to deprecation.
  public_suffix_list.dat
Labels: NOT IOS FB
