Repository publicsuffix/list, pull requests merged in 2021-09, with the labels that each got.

#1388 Adds pages.it.hs-heilbronn.de
  public_suffix_list.dat
Labels: NOT IOS FB

#1400 Updating Cloudera domains
  public_suffix_list.dat
Labels: NOT IOS FB

#1393 add diher.solutions and rss.my.id to the list
  public_suffix_list.dat
Labels: waiting-followup

#1385 Tabitorder.co.il
  public_suffix_list.dat
Labels: IOS-FB?

#1398 Add affinitylottery.org.uk raffleentry.org.uk and weeklylottery.org.uk to public suffix list
  public_suffix_list.dat
Labels: IOS-FB?

#1402 Add barsy.ro to Lukanet Ltd private domains
  public_suffix_list.dat
Labels: waiting-followup, NOT IOS FB

#1390 Added Lokalized domain
  public_suffix_list.dat
Labels: NOT IOS FB

#1406 Roll back diher.solutions PR #1393
  public_suffix_list.dat
Labels: rollback

#1407 Remove: nctu.me
  public_suffix_list.dat
Labels: rollback

#1426 Update (remove) .tn entries
  public_suffix_list.dat
Labels: r=dnsguru, NOT IOS FB

#1421 Add digitaloceanspaces.com & regional subdomains
  public_suffix_list.dat
Labels: r=sleevi, r=dnsguru, NOT IOS FB

#1417 Add sandbox.usercontent.goog
  public_suffix_list.dat
Labels: question, waiting-followup, NOT IOS FB

#1311 add prequalifyme.today to private section
  public_suffix_list.dat
Labels: NOT IOS FB

#1434 Remove clic2000.net from Private Section
  public_suffix_list.dat
Labels: rollback, NOT IOS FB
