Repository publicsuffix/list, pull requests merged in 2021-12, with the labels that each got.

#1405 Adding Hoplix domains
  public_suffix_list.dat
Labels: IOS-FB?, IOS PCM / FB AEM Victim Queue ⌚

#1420 Add 9 BASE, Inc. domains to private section
  public_suffix_list.dat
Labels: IOS-FB?, IOS PCM / FB AEM Victim Queue ⌚

#1462 Please add koobin.events to the PSL
  public_suffix_list.dat
Labels: IOS-FB?, IOS PCM / FB AEM Victim Queue ⌚

#1444 Remove nodum domains
  public_suffix_list.dat
Labels: 😭rollback

#1463 Replace edugit.org with edugit.io and add s3.teckids.org for Teckids
  public_suffix_list.dat
Labels: NOT IOS FB

#1455 Add NoSpamProxy Cloud domain: cloud.nospamproxy.com
  public_suffix_list.dat
Labels: NOT IOS FB

#1457 feat: Add pro.typeform.com to PSL
  public_suffix_list.dat
Labels: NOT IOS FB

#1430 Add encoway domain: eu.encoway.cloud
  public_suffix_list.dat
Labels: NOT IOS FB

#1468 Adding ravendb.cloud domain to allow separation between users
  public_suffix_list.dat
Labels: NOT IOS FB, ❌FAIL - FIX SORTING ⏬
