Repository publicsuffix/list, pull requests merged in 2021-11, with the labels that each got.

#1467 Remove: gb.com
  public_suffix_list.dat
Labels: 😭rollback, NOT IOS FB

#1401 Added FlashDrive.io domain names
  public_suffix_list.dat
Labels: NOT IOS FB

#1480 REMOVAL of virtueeldomein.nl
  public_suffix_list.dat
Labels: r=dnsguru, NOT IOS FB

#1475 Revert "Add amsw.nl private domain to PSL (#929)"
  public_suffix_list.dat
Labels: r=dnsguru, NOT IOS FB
