Repository publicsuffix/list, pull requests merged in 2021-05, with the labels that each got.

#1304 Add authgearapps.com authgear-staging.com
  public_suffix_list.dat
Labels: waiting-followup

#1318 Remove wildcard id.forgerock.io
  public_suffix_list.dat
Labels: question, rollback, waiting-followup

#1306 REMOVE ra-ru.ru, zsew.ru (#1149)
  public_suffix_list.dat
Labels: question, rollback

#1273 Add new frusky.de
  public_suffix_list.dat
Labels: NOT IOS FB

#1299 Added onavstack.net to PRIVATE section of PSL
  public_suffix_list.dat
Labels: NOT IOS FB

#1330 Add jotelulu.cloud
  public_suffix_list.dat
Labels: NOT IOS FB

#1331 Add novecore.site
  public_suffix_list.dat
Labels: NOT IOS FB

#1335 Remove github.dev from PSL
  public_suffix_list.dat
Labels: rollback
