Repository publicsuffix/list, pull requests merged in 2021-07, with the labels that each got.

#1377 Remove uwu.nu
  public_suffix_list.dat
Labels: NOT IOS FB

#1357 Add cdn.prod.atlassian-dev.net
  public_suffix_list.dat
Labels: NOT IOS FB

#1355 Add drr.ac and ju.mp
  public_suffix_list.dat
Labels: waiting-followup

#1374 Adding bitbucket.io pages which render user generated content
  public_suffix_list.dat
Labels: NOT IOS FB

#1375 Add itcouldbewor.se to public suffix list
  public_suffix_list.dat
Labels: NOT IOS FB

#1379 Adding sellfy.store pages which render user generated content
  public_suffix_list.dat
Labels: NOT IOS FB

#1381 Add nog.community
  public_suffix_list.dat
Labels: NOT IOS FB

#1361 add new domains for thingdust AG
  public_suffix_list.dat
Labels: NOT IOS FB, waiting-followup

#1376 Add demo.datadetect.com and instance.datadetect.com
  public_suffix_list.dat
Labels: NOT IOS FB, waiting-followup

#1380 Add YunoHost DynDns domains: ynh.fr
  public_suffix_list.dat
Labels: NOT IOS FB

#1363 Add Supabase domains
  public_suffix_list.dat
Labels: waiting-followup

#1368 Add Spreadshop hosting domains: myspreadshop.com plus country-specific
  public_suffix_list.dat
Labels: IOS-FB?, NOT IOS FB, waiting-followup

#1378 add Adobe Project Helix domains to the list
  public_suffix_list.dat
Labels: NOT IOS FB, waiting-followup

#1359 add eero ddns domains
  public_suffix_list.dat
Labels: waiting-followup
