Repository publicsuffix/list, pull requests merged in 2022-10, with the labels that each got.

#1568 Update existing Replit entries, add `firewalledreplit.co`
  public_suffix_list.dat
Labels: 🩺 pending-validation, NOT IOS FB

#1578 Add `*.on-acorn.io`
  public_suffix_list.dat
Labels: NOT IOS FB

#1601 Add Fastmail user content domain `user.fm`
  public_suffix_list.dat
Labels: NOT IOS FB

#1623 Add Domains from `simplesite.com` et al to one.com subsection
  public_suffix_list.dat
Labels: NOT IOS FB

#1630 Names.of.London is no longer operating the service
  public_suffix_list.dat
Labels: r=dnsguru, 😭rollback, NOT IOS FB

#1639 Fix typos in pull request template
  .github/pull_request_template.md
Labels: r=dnsguru
