Repository publicsuffix/list, pull requests merged in 2022-02, with the labels that each got.

#1512 Add: GDS Managed Domains
  public_suffix_list.dat
Labels: 🩺 pending-validation, waiting-followup, r=dnsguru, DRAFT

#1472 Add `vultrobjects.com` and future regional subdomains
  public_suffix_list.dat
Labels: NOT IOS FB

#1470 add `*.beget.app`
  public_suffix_list.dat
Labels: NOT IOS FB

#1517 Update `.cy` per request from nic.cy in Issue 1516
  public_suffix_list.dat
Labels: NOT IOS FB

#1474 Add `discordsays.com` and `discordsez.com`
  public_suffix_list.dat
Labels: NOT IOS FB

#1478 Add `translated.page`
  public_suffix_list.dat
Labels: NOT IOS FB

#1476 Add `kapsi.fi` to PSL
  public_suffix_list.dat
Labels: NOT IOS FB

#1528 Revises policy links for `.ac` `.io` `.sh` to address issue #1527
  public_suffix_list.dat
Labels: NOT IOS FB

#1490 Add `messwithdns.com`
  public_suffix_list.dat
Labels: NOT IOS FB

#1491 Add `rocky.page`
  public_suffix_list.dat
Labels: NOT IOS FB

#1526 Add `tech.orange`
  public_suffix_list.dat
Labels: r=dnsguru, NOT IOS FB

#1522 Add 105 `lolipop` and `heteml` domains to private section for GMO
  public_suffix_list.dat
Labels: NOT IOS FB

#1508 Add `aivencloud.com`
  public_suffix_list.dat
Labels: NOT IOS FB

#1510 Remove WapBlog Suffix
  public_suffix_list.dat
Labels: 😭rollback

#1493 Add `ktistory.com`
  public_suffix_list.dat
Labels: ❔❔ question, ❌FAIL - FIX SORTING ⏬
