Repository publicsuffix/list, pull requests merged in 2022-03, with the labels that each got.

#1519 Remove `couk.me` and `ukco.me` from private section
  public_suffix_list.dat
Labels: 😭rollback

#1532 Add `musician.io` - updates Staclar entry from #1331
  public_suffix_list.dat
Labels: NOT IOS FB

#1509 Add `typedream.app`
  public_suffix_list.dat
Labels: NOT IOS FB

#1511 Add `deta.app` and `deta.dev`
  public_suffix_list.dat
Labels: NOT IOS FB

#1530 Fix spelling errors in PSL
  public_suffix_list.dat
Labels: NOT IOS FB

#1536 Add: `campaign.gov.uk` (updates #1512)
  public_suffix_list.dat
Labels: NOT IOS FB

#1531 Add domains for `encore.dev`
  public_suffix_list.dat
Labels: NOT IOS FB

#1459 Add `user.localcert.dev`
  public_suffix_list.dat
Labels: ❔❔ question, 🩺 pending-validation, r=sleevi, NOT IOS FB
