Repository publicsuffix/list, pull requests merged in 2022-11, with the labels that each got.

#1638 Remove `gwiddle.co.uk`
  public_suffix_list.dat
Labels: 😭rollback, NOT IOS FB, MAY DESERVE SECURITY REVIEW

#1602 Add `myamaze.net`
  public_suffix_list.dat
Labels: NOT IOS FB

#1499 Update #1385: add `mytabit.co.il` & `mytabit.com` for IOS PCM / FB solution
  public_suffix_list.dat
Labels: IOS-FB?, IOS PCM / FB AEM Victim Queue ⌚

#1582 Add `cf-ipfs.com`, `cloudflare-ipfs.com`, and `r2.dev`
  public_suffix_list.dat
Labels: waiting-followup, NOT IOS FB
