Repository publicsuffix/list, pull requests merged in 2023-09, with the labels that each got.

#1718 Set up permissions to github workflow to least privileges
  .github/workflows/deploy-site.yml
  .github/workflows/tld-update.yml
Labels: MAY DESERVE SECURITY REVIEW, non .dat Change or Coding Review

#1691 Add `wix.run`
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated

#1854 Remove k12.de.us
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, 🚩ICANN (IANA/ICP-3) Section

#1823 Update .fr list, move some subspaces to PRIVATE section listing of smallregistry.net
  public_suffix_list.dat
Labels: NOT IOS FB, ✔️DNS _psl Validated, ✔️Sorting Validated, 🚩ICANN (IANA/ICP-3) Section
