Repository publicsuffix/list, pull requests merged in 2023-06, with the labels that each got.

#1771 Add `{id,io,ai}.vn` for .vn ccTLD in ICANN Section
  public_suffix_list.dat
Labels: r=dnsguru, NOT IOS FB, ✔️DNS _psl Validated, 🚩ICANN (IANA/ICP-3) Section

#1776 Add 63 geographical domains for .vn ccTLD
  public_suffix_list.dat
Labels: r=dnsguru, NOT IOS FB, ✔️DNS _psl Validated, ✔️Sorting Validated, 🚩ICANN (IANA/ICP-3) Section

#1600 AWS Submissions to the Public Suffix List - Q1 2023
  public_suffix_list.dat
Labels: NOT IOS FB, ✔️DNS _psl Validated, ✔️Sorting Validated
