Repository publicsuffix/list, pull requests merged in 2023-02, with the labels that each got.

#1617 Add `autocode.dev`
  public_suffix_list.dat
Labels: NOT IOS FB

#1633 Add Adobe Developer Platform domains `adobeio-static.net` and `adobeioruntime.net`
  public_suffix_list.dat
Labels: NOT IOS FB

#1680 add fastly-edge.com
  public_suffix_list.dat
Labels: NOT IOS FB

#1627 add `canva-apps.com` and `canva-apps.cn`
  public_suffix_list.dat
Labels: NOT IOS FB

#1634 Add Snowflake Inc domains to PRIVATE section
  public_suffix_list.dat
Labels: NOT IOS FB

#1654 Add `it.com`
  public_suffix_list.dat
Labels: NOT IOS FB

#1704 Add `3.azurestaticapps.net` DNS suffix
  public_suffix_list.dat
Labels: NOT IOS FB

#1668 add 47 domains of SAKURA Internet Inc.
  public_suffix_list.dat
Labels: r=dnsguru

#1597 Add `ie.ua`
  public_suffix_list.dat
Labels: NOT IOS FB

#1653 Additional ngrok domains - more `ngrok.io` from #48 + `ngrok.app` `ngrok-free.app` `ngrok.dev` `ngrok-free.dev` `ngrok.pizza`
  public_suffix_list.dat
Labels: MAY DESERVE SECURITY REVIEW
