Repository publicsuffix/list, pull requests merged in 2024-05, with the labels that each got.

#1919 AWS Submissions to the Public Suffix List - Q1 2024
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1821 Add `ngo.us` for the NGO.US Registry
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1795 Add aaa.vodka
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1969 Remove `ghost.io`
  public_suffix_list.dat
Labels: 😭rollback, ✔️DNS _psl Validated, r=simon-friedberger

#1749 Adding regional domain `bielsko.pl`
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1820 Remove Lightmaker Property Manager, Inc. section and domain `app.lmpm.com`
  public_suffix_list.dat
Labels: 😭rollback, ✔️DNS _psl Validated, r=simon-friedberger

#1859 Update `prvcy.page`
  public_suffix_list.dat
Labels: NOT IOS FB, ✔️DNS _psl Validated, ✔️Sorting Validated

#1945 Add `sheezy.games`
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1865 Add "zeabur.app"
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1934 Add observablehq.cloud
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1950 Add `box.ca` (Whatbox)
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1958 Add notion.site as private eTLD
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1964 Add web.val.run and express.val.run to PSL
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1974 Add Clever Cloud's domains for customers
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1947 Add `*.hosted.app`
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1975 Add Expo domains
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1933 Add Github workflow to check _psl DNS entries on PRs
  .github/workflows/check_pr.yml
  tools/pr_checker/check_dns.py
  tools/pr_checker/requirements.txt
  tools/pr_checker/test_psl_01.dat
  tools/pr_checker/test_psl_02.dat
Labels: non .dat Change or Coding Review

#1971 Add `wixstudio.com`
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1970 Add `hypernode.io` domain
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger
