Repository publicsuffix/list, pull requests merged in 2024-01, with the labels that each got.

#1802 Update code builder domains with the canary partner
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated

#1874 Update Adobe entries with aem.live and aem.page for former Project Helix
  public_suffix_list.dat
Labels: NOT IOS FB, ✔️DNS _psl Validated, ✔️Sorting Validated

#1792 Update Platform.sh section - add `upsunapp.com`, `upsun.app` domains, remove `bc.platform.sh`
  public_suffix_list.dat
Labels: NOT IOS FB, ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1920 Add pages.gay
  public_suffix_list.dat
Labels: r=dnsguru, ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger
