Repository publicsuffix/list, pull requests merged in 2024-07, with the labels that each got.

#2006 Add Craft Docs Domain
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1948 Add `hatenablog.com`, etc.
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#2016 Add `p.tawk.email` and `p.tawkto.email` domains
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated

#2026 Add Servebolt AS shared domain: servebolt.cloud
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated

#2070 Remove `awsmppl.com` to rollback #900 (expired domain, malicious)
  public_suffix_list.dat
Labels: r=dnsguru
