Repository publicsuffix/list, pull requests merged in 2024-08, with the labels that each got.

#2064 remove `bitbridge.net`
  public_suffix_list.dat
Labels: 😭rollback

#2082 Add `mafelo.net`
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#2076 Update public_suffix_list.dat
  public_suffix_list.dat
Labels: ❌invalid, ❌FAIL - DOMAIN NOT 2Y+, ❌FAIL - SHORT ORG INFO/RATIONALE

#2067 add `wdh.app`
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#2085 add ggff.net and filegear-sg.me
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#2083 Add IONOS product domains
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#2107 Add routingthecloud.com/.net/.org
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#2063 remove `bip.sh`
  public_suffix_list.dat
Labels: ❔❔ question, waiting-followup, 😭rollback, ✔️DNS _psl Validated
