Repository publicsuffix/list, pull requests merged in 2024-06, with the labels that each got.

#1963 Add Cloudflare CNAME setup domains
  public_suffix_list.dat
Labels: r=dnsguru, ✔️DNS _psl Validated, ✔️Sorting Validated

#1980 Add heiyu.space
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1984 add .ind.mom
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger, Autocheck Success

#1959 Add relay.evervault.app and relay.evervault.dev
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1982 Add Strapi domains
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1845 mytuleap.com, tuleap-partners.com: update contact information
  public_suffix_list.dat
Labels: ❌FAIL - DNS VALIDATION

#1979 Add `madethis.site`
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1995 Reattach of.by to the Belarus ccTLD block
  public_suffix_list.dat
Labels: r=simon-friedberger

#1992 Add `as.sh.cn`
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1991 Add netfy.app
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1957 Add `wpsquared.site` and `wp2.host` to private section
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1941 Salesforce crm dev
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1830 Add `obl.ong`
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#2004 Add Raidboxes GmbH to the list
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated

#1978 Add `durumis.com`
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger, Autocheck Success

#2013 Merge WebPros domains in the same section
  public_suffix_list.dat
Labels: r=dnsguru, ✔️DNS _psl Validated, ✔️Sorting Validated
