Repository publicsuffix/list, pull requests merged in 2024-03, with the labels that each got.

#1760 Update Rad Web Hosting Domains section - add myradweb.net, servername.us
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1720 Add 3 Streak domains
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1722 Add `webflow.io` and `webflowtest.io`
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1618 Add `*.c.ts.net.`
  public_suffix_list.dat
Labels: NOT IOS FB, ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1664 Add `f5.si`
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1773 Add `ewp.live` (EasyWP)
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1804 Add `modx.dev`
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1785 Add STACKIT subdomains (`runs.onstackit.cloud`, `stackit.gg`, `stackit.rocks`, `stackit.run`, `stackit.zone`)
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1824 Add `adaptable.app`
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1895 additional ngrok domain - add `ngrok.pro`
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1904 Add on.crisp.email (Crisp IM SAS)
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1739 add `*.my.canvasite.cn` and `*.my.canva.site`
  public_suffix_list.dat
Labels: NOT IOS FB, ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1944 Removing wildcard for cloudapp.azure.com
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, r=simon-friedberger

#1940 GD - graphic.design
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1548 add `nftstorage.link`
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1616 Update name for `info.cx`
  public_suffix_list.dat
Labels: r=simon-friedberger

#1625 Add `*.ir.md`
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger
