Repository publicsuffix/list, pull requests merged in 2024-02, with the labels that each got.

#1768 Homebase requested the addition of id.pub kin.one kin.pub
  public_suffix_list.dat
Labels: r=dnsguru, ✔️DNS _psl Validated, ✔️Sorting Validated

#1876 AWS Submissions to the Public Suffix List - Q4 2023
  public_suffix_list.dat
Labels: r=dnsguru, NOT IOS FB, ✔️DNS _psl Validated, ✔️Sorting Validated

#1840 Removal of `blog.kg` from private section
  public_suffix_list.dat
Labels: r=dnsguru, 😭rollback, NOT IOS FB, ✔️DNS _psl Validated, ✔️Sorting Validated

#1891 Azure updates for Microsoft Corporate Domains
  public_suffix_list.dat
Labels: r=dnsguru, NOT IOS FB, ✔️DNS _psl Validated, ✔️Sorting Validated

#1915 add 12CHARS to private domains
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1916 Add panel.dev
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1872 Brave Submissions to the Public Suffix List - Q4 2023
  public_suffix_list.dat
Labels: NOT IOS FB, ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1614 Add `aliases121.com`
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1666 Add `flutterflow.app`
  public_suffix_list.dat
Labels: NOT IOS FB, ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1907 Add ZAP-Hosting Domains
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1926 Add a2hosted.com and cpserver.com suffix to private section
  public_suffix_list.dat
Labels: ❔❔ question, ✔️DNS _psl Validated, ✔️Sorting Validated

#1740 Update public_suffix_list.dat for scw.cloud cockpit product subdomains
  public_suffix_list.dat
Labels: ❌FAIL - FIX SORTING ⏬, ✔️DNS _psl Validated

#1737 Added Cyclic Software
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1892 Add cprapid.com suffix to private section
  public_suffix_list.dat
Labels: NOT IOS FB
