Repository publicsuffix/list, pull requests merged in 2024-04, with the labels that each got.

#1882 Add cdn77-storage.com and rsc.contentproxy9.cz
  public_suffix_list.dat
Labels: NOT IOS FB, ✔️DNS _psl Validated, r=simon-friedberger

#1651 ADD: `can.re`
  public_suffix_list.dat
Labels: NOT IOS FB, ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1924 Add wadl.top
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1798 add getlocalcert.net domains
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1797 Add `nimsite.uk`
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1648 Add `preview.csb.app` and `csb.app`
  public_suffix_list.dat
Labels: NOT IOS FB, ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1743 Update Snowflake Inc domains in PRIVATE section
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1880 Add darklang.io
  public_suffix_list.dat
Labels: NOT IOS FB, ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1826 add `scrypted.io`
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1844 Remove unused suffix (123sait.ru)
  public_suffix_list.dat
Labels: 😭rollback, ✔️DNS _psl Validated, r=simon-friedberger

#1825 Add `heliohost.us`, `helioho.st`
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1783 Add `runcontainers.dev` domain
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1742 Add grayjayleagues.com
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1672 Add `is-cool.dev`, `is-local.org`, `is-not-a.dev` and `localplayer.dev`
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1839 Add `unison-services.cloud`
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1939 Add StackBlitz
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1949 chore: add `is-a.dev`
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1831 Add `framer.ai`
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1761 PSL: Adding myfritz.link (follow up PR#77)
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1841 Removing ravendb.me - unused & expired domain
  public_suffix_list.dat
Labels: 😭rollback, r=simon-friedberger

#1589 Add `cloudscale.ch` domains
  public_suffix_list.dat
Labels: 🩺 pending-validation, NOT IOS FB, MAY DESERVE SECURITY REVIEW, ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1860 Add `rt.ht`
  public_suffix_list.dat
Labels: NOT IOS FB, ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1755 Add ```us.kg```
  public_suffix_list.dat
Labels: ❌FAIL - DOMAIN NOT 2Y+, 👻 about to timeout

#1935 Jouwweb public suffixes
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1960 Drop old pcarrier.ca Software Inc. domains
  public_suffix_list.dat
Labels: r=simon-friedberger

#1966 Removing cloudapp.azure.com from PSL
  public_suffix_list.dat
Labels: r=dnsguru, 😭rollback, NOT IOS FB, ✔️DNS _psl Validated, ✔️Sorting Validated

#1837 add qnap entries to existing section (`myqnapcloud.cn` , `mycloudnas.com`, `mynascloud.com`)
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger

#1762 Add shop.brendly.hr
  public_suffix_list.dat
Labels: ✔️DNS _psl Validated, ✔️Sorting Validated, r=simon-friedberger
