Repository publicsuffix/list, pull requests merged in 2025-05, with the labels that each got.

#2420 Actualización de lista de extensiones del dominio ec en orden alfabético
  public_suffix_list.dat
Labels: 🚩ICANN (IANA/ICP-3) Section

#2450 Add encr.app and lp.dev subdomains
  public_suffix_list.dat
Labels: ❌FAIL - DNS VALIDATION

#2424 Add icp0.io / icp1.io / caffeine.site / caffeine.website for Internet Computer domains
  public_suffix_list.dat
Labels: ❌FAIL - DOMAIN NOT 2Y+
